### ISSUE TITLE
好兄弟该怎么跑起来啊，能留个联系方式吗

### ISSUE THREAD

**Issue by szhnzjk** [shuaichaochao/HybridHash#3]
可能是电脑太拉了或者我版本下的有问题。方便留个联系方式请教一下吗

**Comment by shuaichaochao** [comment]
> 可能是电脑太拉了或者我版本下的有问题。方便留个联系方式请教一下吗

apex 0.1
cudatoolkit 11.3.1
loguru 0.7.2
ml-collections 0.1.1
numpy 1.24.3
numpy-base 1.24.3
pillow 10.2.0
pip 21.2.2
ptflops 0.7.2
python 3.8.3
torch 1.12.1
torchaudio 0.12.1
torchvision 0.13.1
timm 0.6.13
这是一些必要的环境。其它缺少的包程序会提醒你。

**Comment by szhnzjk** [comment]
OKK。跑起来了。谢谢好哥哥了
